/* INITIALIZE DATABASE */
CREATE DATABASE IF NOT EXISTS ryan_nguyen_Lab05;

/* Q1 */
CREATE TABLE STUDENT_INFO (
    ID          INT(10)         PRIMARY KEY,
    NAME        VARCHAR(100)    NOT NULL,
    DOB         DATE            NOT NULL,
    INCOME      DECIMAL(10,2)   NOT NULL,
    COURSE_ID   INT(5)          NOT NULL
);

/* Q2 */
CREATE TABLE COURSE_INFO (
    ID          INT(10)         PRIMARY KEY,
    NAME        VARCHAR(100)    NOT NULL,
    LOCATION    VARCHAR(200)    NOT NULL,
    STARTDATE   DATE            NOT NULL,
    TYPE        VARCHAR(100)    NOT NULL
);

/* Q3 */
ALTER TABLE STUDENT_INFO ADD ADDRESS VARCHAR(200) NULL;

/* Q4 */
ALTER TABLE COURSE_INFO MODIFY NAME VARCHAR(200);

/* Q5 */
RENAME TABLE STUDENT_INFO TO STUDENT;

/* Q6 */
RENAME TABLE COURSE_INFO TO COURSE;

/* Q7 */
INSERT INTO STUDENT (ID, NAME, DOB, INCOME, COURSE_ID, ADDRESS)
    VALUES (1, 'JOHN', '1998-05-01', 1200, 100, 'NORTH');
INSERT INTO STUDENT (ID, NAME, DOB, INCOME, COURSE_ID, ADDRESS)
    VALUES (2, 'MIKE', '2000-08-15', 1100.15, 200, 'WEST');
INSERT INTO STUDENT (ID, NAME, DOB, INCOME, COURSE_ID, ADDRESS)
    VALUES (3, 'SAM', '1997-11-01', 500, 100, 'SOUTH');

/* Q8 */
INSERT INTO COURSE (ID, NAME, LOCATION, STARTDATE, TYPE)
    VALUES (100, 'FUNDAMENTAL OF WEB DEVELOPMENT', 'AZRIELLI PAVILION', '2023-09-10', 'MANDATORY');
INSERT INTO COURSE (ID, NAME, LOCATION, STARTDATE, TYPE)
    VALUES (300, 'ANALYTICAL METHODS', 'TORY BUILDING', '2023-09-17', 'ELECTIVE');
INSERT INTO COURSE (ID, NAME, LOCATION, STARTDATE, TYPE)
    VALUES (500, 'JAVA PROGRAMMING', 'TORY BUILDING', '2023-09-17', 'ELECTIVE');
INSERT INTO COURSE (ID, NAME, LOCATION, STARTDATE, TYPE)
    VALUES (700, 'C++ PROGRAMMING', 'PATTERSON HALL', '2023-09-10', 'ELECTIVE');

/* Q9 */
UPDATE STUDENT
SET INCOME = 1000
WHERE ID = 2;

/* Q10 */
UPDATE COURSE
SET LOCATION = 'PATTERSON HALL'
WHERE ID = 100;

/* Q11 */
DELETE FROM STUDENT
WHERE ID = 2;

/* Q12 */
DELETE FROM COURSE
WHERE ID = 300;

/* Q13 */
SELECT * FROM STUDENT;

/* Q15 */
SELECT NAME, DOB, INCOME FROM STUDENT;

/* Q17 */
SELECT ID, NAME, DOB, INCOME FROM STUDENT WHERE INCOME > 600;

/* Q19 */
SELECT STUDENT.ID, STUDENT.NAME, STUDENT.DOB, COURSE.NAME
FROM STUDENT
JOIN COURSE ON STUDENT.COURSE_ID=COURSE.ID;

/* Q21 */
TRUNCATE TABLE STUDENT;

/* Q23 */
DROP TABLE STUDENT;

/* Part 4 */
CREATE TABLE game_details (
    game_ID             INT(10)         PRIMARY KEY     AUTO_INCREMENT,
    game_name           VARCHAR(100)    NOT NULL,
    release_date        DATE            NOT NULL,
    game_price          DECIMAL(10,2)   NOT NULL,
    game_description    TEXT            NOT NULL
);
